ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryWard" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryArea" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryLandmark" TEXT;
